tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "bramstein/webfonttools"
tap "buo/cask-upgrade"
tap "ringohub/redis-cli"

brew "mas"

# Utilities
brew "ack"
brew "awscli"
brew "coreutils"
brew "findutils"
brew "gifsicle"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnupg"
brew "grep"
brew "htop"
brew "imagemagick"
brew "jpegoptim"
brew "jq"
brew "lua"
brew "lynx"
brew "moreutils"
brew "openssh"
brew "optipng"
brew "p7zip"
brew "pigz"
brew "pipenv"
brew "pkg-config"
brew "pngquant"
brew "pv"
brew "rclone"
brew "redis-cli"
brew "rename"
brew "rlwrap"
brew "screen"
brew "ssh-copy-id"
brew "svgo"
brew "svn"
brew "tree"
brew "vbindiff"
brew "vim"
brew "wget"
brew "zopfli"
brew "zsh"

# Fonts
brew "sfnt2woff"
brew "sfnt2woff-zopfli"
brew "woff2"
cask "font-fira-code"
cask "font-lato"
cask "font-source-code-pro"

# PHP
brew "php@7.4"
brew "php@8.0"
brew "composer"
cask "ray"
cask "tinkerwell"

# R
brew "r"
cask "zulu15"


# Apps
mas "Magnet", id: 441258766
mas "Blackmagic Disk Speed Test", id: 425264550

cask "1password"
cask "alfred"
cask "bartender"
cask "caffeine"
cask "dash"
cask "dbngin"
cask "discord"
cask "evernote"
cask "freedom"
cask "garmin-express"
cask "geekbench"
cask "github"
cask "google-chrome"
cask "istat-menus"
cask "jetbrains-toolbox"
cask "mactex"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "logitech-options"
cask "nova"
cask "rstudio"
cask "slack"
cask "sonos"
cask "spotify"
cask "sublime-merge"
cask "sublime-text"
cask "tableplus"
cask "transmit"
cask "visual-studio-code"
cask "zoom"
cask "zotero"
