Rscript -e 'install.packages("devtools", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("remotes", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("tidyverse", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("pkgbuild", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("lme4", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("remotes", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("dagitty", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("bookdown", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("ggdag", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("mvtnorm", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("coda", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("shape", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))'
Rscript -e 'install.packages("rstan", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("brms", repos="https://cloud.r-project.org")'
Rscript -e 'devtools::install_github("rmcelreath/rethinking")'

# OHDSI
Rscript -e 'install.packages("DatabaseConnector", repos="https://cloud.r-project.org")'
Rscript -e 'install.packages("DatabaseConnector", repos="https://cloud.r-project.org")'